force-app/main/default/objects/Corporate_Document__c/Corporate_Document__c.object-meta.xml
<CustomObject>
    <description>Corporate Document Objects stores the Uncompleted Documents</description>
    <label>Corporate Document</label>
    <nameField>
        <label>Document</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Corporate Document</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Corporate_Document__c/fields/Document_Template__c.field-meta.xml
<CustomField>
    <fullName>Document_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LookUp to Document Template to store the template as draft</description>
    <label>Document Template</label>
    <referenceTo>Document_Template__c</referenceTo>
    <relationshipLabel>Corporate Document</relationshipLabel>
    <relationshipName>Corporate_Document</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Esign__c/Document_Esign__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Document Esign</label>
</CustomObject>

force-app/main/default/objects/Document_Esign__c/fields/Esign_Webhook_URL__c.field-meta.xml
<CustomField>
    <fullName>Esign_Webhook_URL__c</fullName>
    <description>Esign Webhook URL to be called by callout.</description>
    <label>Esign Webhook URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Document_Template__c/Document_Template__c.object-meta.xml
<CustomObject>
    <description>Document Template object to store all the different type of forms (Parent of Document Content Object)</description>
    <label>Document Template</label>
    <nameField>
        <label>Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/PDFGeneratorControllerTest.cls
@isTest
public class PDFGeneratorControllerTest {
    @isTest
    static void testSaveAsPDFAttachment() {
        User docupadUser = TestUtils.generateDocuPadUserForTest();
        System.runAs(docupadUser) {
            List<Account> accList = TestDataFactory.createAccounts(1, 'Test Account', true);//
            List<Document_Template__c> templateList = TestDataFactory.createTemplates(1, 'Demo Template', '', true);
            List<Corporate_Document__c> docList = TestDataFactory.createDocuments(1, '', templateList[0].Id, true);
            TestDataFactory.createSectionsForDocument(2, 'Section', docList[0].Id, true);
            TestDataFactory.createSectionsForDocument(2, 'Section', docList[0].Id, true);
            PDFGeneratorController.saveAsPDFAttachment(accList[0].Id, docList[0].Id, 'Demo Document 1');
            PDFGeneratorController.saveAsPDFAttachment(accList[0].Id, docList[0].Id, 'Demo Document 2');
            List<ContentDocumentLink> docLinklist = [SELECT Id FROM ContentDocumentLink WHERE LinkedEntityId = :accList[0].Id];
            System.assertEquals(docLinklist.size(), 2);
        }
    }
  @isTest
    static void testSaveDocumentAndSendForEsign() {
        User docupadUser = TestUtils.generateDocuPadUserForTest();
        System.runAs(docupadUser) {
            Document_Esign__c docEsgn = new Document_Esign__c();
            docEsgn.Esign_Webhook_URL__c = 'https://hook.integromat.com/jbem7amsmxffleh7yhvzs42rq3ruqg8a?service=Zoho+Esign';
            insert docEsgn;
            List<Account> accList = TestDataFactory.createAccounts(1, 'Test Account', true);//
            List<Document_Template__c> templateList = TestDataFactory.createTemplates(1, 'Demo Template', '', true);
            List<Corporate_Document__c> docList = TestDataFactory.createDocuments(1, '', templateList[0].Id, true);
            TestDataFactory.createSectionsForDocument(2, 'Section', docList[0].Id, true);
            TestDataFactory.createSectionsForDocument(2, 'Section', docList[0].Id, true);
            Test.setMock(HttpCalloutMock.class, new WebhookCalloutHttpCalloutMockGenegrator()); 
            PDFGeneratorController.saveDocumentAndSendForEsign(accList[0].Id, docList[0].Id, 'Demo Document 1', 'Test Service', 'Test Approver', 'test@gmail.com');
            List<ContentDocumentLink> docLinklist = [SELECT Id FROM ContentDocumentLink WHERE LinkedEntityId = :accList[0].Id];
            System.assertEquals(docLinklist.size(), 1);
        }
    }
}