force-app/main/default/objects/Document_Content__c/Document_Content__c.object-meta.xml
<CustomObject>
    <description>Content Objects holds all the content of the Form (Child of Form Object)</description>
    <label>Document Content</label>
    <nameField>
        <label>Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Content</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Content__c/fields/Content_Type__c.field-meta.xml
<CustomField>
    <fullName>Content_Type__c</fullName>
    <description>To Differentiate body content other non body contents like Header, Footer, Page Break and Blank Page.</description>
    <label>Content Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Body</fullName>
                <default>true</default>
                <label>Body</label>
            </value>
            <value>
                <fullName>Header</fullName>
            </value>
            <value>
                <fullName>Footer</fullName>
            </value>
            <value>
                <fullName>Page Break</fullName>
            </value>
            <value>
                <fullName>Blank Page</fullName>
            </value>
            <value>
                <fullName>Related Records</fullName>
            </value>
            <value>
                <fullName>Custom Content</fullName>
            </value>
            <value>
                <fullName>Signature</fullName>
                <isActive>false</isActive>
                <label>Signature</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Content__c/fields/Document_Template__c.field-meta.xml
<CustomField>
    <fullName>Document_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up to the document template object, in order to relate section content to the document template.</description>
    <label>Document Template</label>
    <referenceTo>Document_Template__c</referenceTo>
    <relationshipLabel>Document Content</relationshipLabel>
    <relationshipName>TempContents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Content__c/fields/Reference_Field__c.field-meta.xml
<CustomField>
    <fullName>Reference_Field__c</fullName>
    <description>Reference Field name whose data will be replaced with placeholder content.</description>
    <label>Reference Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Template__c/Document_Template__c.object-meta.xml
<CustomObject>
    <description>Document Template object to store all the different type of forms (Parent of Document Content Object)</description>
    <label>Document Template</label>
    <nameField>
        <label>Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Template__c/fields/Parent_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_Object_Name__c</fullName>
    <label>Object</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LookupControllerTest.cls
@isTest
public class LookupControllerTest {
    @isTest
    public static void testfindRecords() {
        User docupadUser = TestUtils.generateDocuPadUserForTest();
        System.runAs(docupadUser) {
            List<Document_Template__c> tempList = TestDataFactory.createTemplates(1, 'test template', ' ', true);
            List<Document_Content__c> sectionList = TestDataFactory.createSections(8, 'Section', tempList[0].Id, true);
            List<Document_Content__c> fieldList = TestDataFactory.createFields(1,'Field', sectionList, true);
            List<Document_Content__c> sectionLisToUpdate = new List<Document_Content__c>();
            Document_Content__c documentContent = fieldList[0];
            documentContent.Reference_Field__c = 'Contact.Birthdate';
            sectionLisToUpdate.add(documentContent);
            Document_Content__c docContent2 = sectionList[1];
            docContent2.Content_Type__c = 'Header';
            sectionLisToUpdate.add(docContent2);
            Document_Content__c docContent3 = sectionList[2];
            docContent3.Content_Type__c = 'Footer';
            sectionLisToUpdate.add(docContent3);
            Document_Content__c docContent4 = sectionList[3];
            docContent4.Content_Type__c = 'Related Records';
            sectionLisToUpdate.add(docContent4);
            UPDATE sectionLisToUpdate;
            fieldList.add(documentContent);
            String searchKey = 'Section';
            String objectName = 'Document_Content__c';
            List<Document_Content__c> retrunDocObj = LookupController.findRecords(searchKey, objectName);
            System.assert(retrunDocObj != Null);
        }
    }

    @isTest
    public static void testGetDocumentContentSectionWrapper() {
        User docupadUser = TestUtils.generateDocuPadUserForTest();
        System.runAs(docupadUser) {
            List<Document_Template__c> tempList = TestDataFactory.createTemplates(1, 'test template', ' ', true);
            List<Document_Content__c> sectionList = TestDataFactory.createSections(8, 'Section', tempList[0].Id, true);
            List<Document_Content__c> fieldList = TestDataFactory.createFields(1,'Field', sectionList, true);
            List<Document_Content__c> sectionLisToUpdate = new List<Document_Content__c>();
            Document_Content__c documentContent = fieldList[0];
            documentContent.Reference_Field__c = 'Contact.Birthdate';
            sectionLisToUpdate.add(documentContent);
            Document_Content__c docContent2 = sectionList[1];
            docContent2.Content_Type__c = 'Header';
            sectionLisToUpdate.add(docContent2);
            Document_Content__c docContent3 = sectionList[2];
            docContent2.Content_Type__c = 'Footer';
            sectionLisToUpdate.add(docContent3);
            Document_Content__c docContent4 = sectionList[3];
            docContent4.Content_Type__c = 'Related Records';
            sectionLisToUpdate.add(docContent4);
            UPDATE sectionLisToUpdate;
            fieldList.add(documentContent);
            Domain.SectionWrapper returnedSectionWrapper = LookupController.getDocumentContentSectionWrapper(sectionList[0].Id);
            Domain.SectionWrapper returnedSectionWrapper2 = LookupController.getDocumentContentSectionWrapper(sectionList[1].Id);
            Domain.SectionWrapper returnedSectionWrapper3 = LookupController.getDocumentContentSectionWrapper(docContent4.Id);
            System.assert(returnedSectionWrapper != Null);
            System.assert(returnedSectionWrapper2 != Null);
            System.assert(returnedSectionWrapper3 != Null);
        }
    }
    
   @isTest
    public static void testFetchSectionsAndTemplateDetails() {
        User docupadUser = TestUtils.generateDocuPadUserForTest();
        System.runAs(docupadUser) {
            List<Document_Template__c> tempList = TestDataFactory.createTemplates(1, 'test template', ' ', true);
            tempList[0].Parent_Object_Name__c = 'Account';
            update tempList[0];
            List<Document_Content__c> sectionList = TestDataFactory.createSections(8, 'Section', tempList[0].Id, true);
            List<Document_Content__c> fieldList = TestDataFactory.createFields(1,'Field', sectionList, true);
            List<Document_Content__c> sectionLisToUpdate = new List<Document_Content__c>();
            Document_Content__c documentContent = fieldList[0];
            documentContent.Reference_Field__c = 'Contact.Birthdate';
            sectionLisToUpdate.add(documentContent);
            Document_Content__c docContent2 = sectionList[1];
            docContent2.Content_Type__c = 'Header';
            sectionLisToUpdate.add(docContent2);
            Document_Content__c docContent3 = sectionList[2];
            docContent2.Content_Type__c = 'Footer';
            sectionLisToUpdate.add(docContent3);
            Document_Content__c docContent4 = sectionList[3];
            docContent4.Content_Type__c = 'Related Records';
            sectionLisToUpdate.add(docContent4);
            UPDATE sectionLisToUpdate;
            fieldList.add(documentContent);
            Test.startTest();
            List<Document_Content__c> retrunDocObj = LookupController.fetchSectionsAndTemplateDetails('Section','Account');
            System.assert(retrunDocObj != Null);
            Test.stopTest();
        }
    }
}