force-app/main/default/objects/Document_Content__c/Document_Content__c.object-meta.xml
<CustomObject>
    <description>Content Objects holds all the content of the Form (Child of Form Object)</description>
    <label>Document Content</label>
    <nameField>
        <label>Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Content</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Content__c/fields/Document_Template__c.field-meta.xml
<CustomField>
    <fullName>Document_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up to the document template object, in order to relate section content to the document template.</description>
    <label>Document Template</label>
    <referenceTo>Document_Template__c</referenceTo>
    <relationshipLabel>Document Content</relationshipLabel>
    <relationshipName>TempContents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Template__c/Document_Template__c.object-meta.xml
<CustomObject>
    <description>Document Template object to store all the different type of forms (Parent of Document Content Object)</description>
    <label>Document Template</label>
    <nameField>
        <label>Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/AdvanceEditorControllerTest.cls
@isTest
private class AdvanceEditorControllerTest {
    @isTest
    public static void testAdvanceEditorControllerSave() {
        User docupadUser = TestUtils.generateDocuPadUserForTest();
        System.runAs(docupadUser) {
            List<Document_Template__c> templateList = TestDataFactory.createTemplates(1, 'Demo Template', '', true);
            List<Document_Content__c> sectionList = TestDataFactory.createSections(2, 'Section', templateList[0].Id, false);
            FormHandler.upsertDocContentList(sectionList);
            AdvanceEditorController objAdvanceEditorController = new AdvanceEditorController();
            objAdvanceEditorController.getSectionContent();
            objAdvanceEditorController.save();
            List<Document_Content__c> newSectionList = new List<Document_Content__c>();
            newSectionList = [SELECT Id, Name FROM Document_Content__c];
            System.assertEquals(2, newSectionList.size(), 'count matched');
        }
    }

}