force-app/main/default/objects/Document_Content__c/Document_Content__c.object-meta.xml
<CustomObject>
    <description>Content Objects holds all the content of the Form (Child of Form Object)</description>
    <label>Document Content</label>
    <nameField>
        <label>Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Content</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Content__c/fields/Section_Content__c.field-meta.xml
<CustomField>
    <fullName>Section_Content__c</fullName>
    <description>Holds the section contents in the form of html markup text.</description>
    <label>Section Content</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/AdvanceEditorController.cls
/**
** Author      :   Ceptes Software Pvt. Ltd
** Description :   This class is used for TinyMCE Editor VF Page.
**/


global with sharing class AdvanceEditorController {
    private final Document_Content__c sectionContent;
 
    global AdvanceEditorController() {
        Id sectionId;
        if(!Test.isRunningTest()) {
            sectionId = ApexPages.currentPage().getParameters().get('recordId');
        } else {
            // As we don't have apex page as part of package, and mock data created in test class
            sectionId = [SELECT Id FROM Document_Content__c WITH SECURITY_ENFORCED LIMIT 1].Id;
        }
        sectionContent = [SELECT Id, Name, Section_Content__c 
            FROM Document_Content__c 
            WHERE Id = :sectionId
            WITH SECURITY_ENFORCED];
    }
	
    /**
     * @description  :   Updates the document sections
     * @param        :   void
     * @return       :   Document_Content__c (section content)
     */
    global Document_Content__c getSectionContent() {
        return sectionContent;
    }

    /**
     * @description  :   Updates the document sections 
     * @param        :   void
     * @return       :   void
     */
    global PageReference save() {
        SObjectAccessDecision securityDecision = Security.stripInaccessible(
                                         AccessType.UPDATABLE, new List<Document_Content__c> {sectionContent});
        UPDATE securityDecision.getRecords();
        return Null;
    }
}