force-app/main/default/objects/App_Settings__c/App_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>DocuPad App Settings</description>
    <label>App Settings</label>
</CustomObject>

force-app/main/default/objects/App_Settings__c/fields/Named_Cred__c.field-meta.xml
<CustomField>
    <fullName>Named_Cred__c</fullName>
    <description>If you have selected &quot;Use Named Cred&quot; then specify Name Credential name</description>
    <inlineHelpText>&quot;Name Credential&quot; name</inlineHelpText>
    <label>Named Cred</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/App_Settings__c/fields/RestAPIVersion__c.field-meta.xml
<CustomField>
    <fullName>RestAPIVersion__c</fullName>
    <description>This is used to specify Rest API Version</description>
    <inlineHelpText>Rest API Version</inlineHelpText>
    <label>RestAPIVersion</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/App_Settings__c/fields/Use_Named_Cred__c.field-meta.xml
<CustomField>
    <fullName>Use_Named_Cred__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enabling this option means to retrieve the meta data information use Named Cred and Provide Name Cred Name</description>
    <inlineHelpText>Named Cred and Provide Name Cred Name</inlineHelpText>
    <label>Use Named Cred</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Corporate_Document__c/Corporate_Document__c.object-meta.xml
<CustomObject>
    <description>Corporate Document Objects stores the Uncompleted Documents</description>
    <label>Corporate Document</label>
    <nameField>
        <label>Document</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Corporate Document</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Corporate_Document__c/fields/Document_Stage__c.field-meta.xml
<CustomField>
    <fullName>Document_Stage__c</fullName>
    <description>Stage of Document</description>
    <label>Document Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Obsolete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Corporate_Document__c/fields/Document_Template__c.field-meta.xml
<CustomField>
    <fullName>Document_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LookUp to Document Template to store the template as draft</description>
    <label>Document Template</label>
    <referenceTo>Document_Template__c</referenceTo>
    <relationshipLabel>Corporate Document</relationshipLabel>
    <relationshipName>Corporate_Document</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Content__c/Document_Content__c.object-meta.xml
<CustomObject>
    <description>Content Objects holds all the content of the Form (Child of Form Object)</description>
    <label>Document Content</label>
    <nameField>
        <label>Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Content</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Content__c/fields/Alignment__c.field-meta.xml
<CustomField>
    <fullName>Alignment__c</fullName>
    <description>To Specify alignment of page header/footer content.</description>
    <label>Alignment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Left</fullName>
            </value>
            <value>
                <fullName>Center</fullName>
            </value>
            <value>
                <fullName>Right</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Content__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Self LookUp as it has multiple content fields.</description>
    <label>Content</label>
    <referenceTo>Document_Content__c</referenceTo>
    <relationshipLabel>Document Content</relationshipLabel>
    <relationshipName>Contents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Content__c/fields/Corporate_Document__c.field-meta.xml
<CustomField>
    <fullName>Corporate_Document__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up to a document.</description>
    <label>Corporate Document</label>
    <referenceTo>Corporate_Document__c</referenceTo>
    <relationshipLabel>Document Content</relationshipLabel>
    <relationshipName>CorpContents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Content__c/fields/Document_Template__c.field-meta.xml
<CustomField>
    <fullName>Document_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up to the document template object, in order to relate section content to the document template.</description>
    <label>Document Template</label>
    <referenceTo>Document_Template__c</referenceTo>
    <relationshipLabel>Document Content</relationshipLabel>
    <relationshipName>TempContents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Content__c/fields/Field_Type__c.field-meta.xml
<CustomField>
    <fullName>Field_Type__c</fullName>
    <description>To get the Field-Type from the user and to render accordingly</description>
    <label>Field Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>String</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>tel</fullName>
                <label>Telephone</label>
            </value>
            <value>
                <fullName>Textarea</fullName>
            </value>
            <value>
                <fullName>CheckBox</fullName>
                <isActive>false</isActive>
                <label>CheckBox</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Content__c/fields/Order_Sequence__c.field-meta.xml
<CustomField>
    <fullName>Order_Sequence__c</fullName>
    <description>Order in which the section content should be displayed for a template or document.</description>
    <label>Order Sequence</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Document_Content__c/fields/Placeholder_Content__c.field-meta.xml
<CustomField>
    <fullName>Placeholder_Content__c</fullName>
    <description>Placeholder Content which will be replaced with the user input in the section content.</description>
    <inlineHelpText>Placeholder Content which will be replaced with the user input in the section content(without brackets [ ]).</inlineHelpText>
    <label>Placeholder Content</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Content__c/fields/Reference_Field__c.field-meta.xml
<CustomField>
    <fullName>Reference_Field__c</fullName>
    <description>Reference Field name whose data will be replaced with placeholder content.</description>
    <label>Reference Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Content__c/fields/Section_Content__c.field-meta.xml
<CustomField>
    <fullName>Section_Content__c</fullName>
    <description>Holds the section contents in the form of html markup text.</description>
    <label>Section Content</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Document_Content__c/fields/Template_Type__c.field-meta.xml
<CustomField>
    <fullName>Template_Type__c</fullName>
    <description>The category or type of template.</description>
    <label>Template Type</label>
    <length>88</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Content__c/fields/Visibility__c.field-meta.xml
<CustomField>
    <fullName>Visibility__c</fullName>
    <description>Decides the visibility of header/footer content of the page to be on All The Pages or on First Page Only.</description>
    <label>Visibility</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>First Page Only</fullName>
            </value>
            <value>
                <fullName>All The Pages</fullName>
            </value>
            <value>
                <fullName>First And Last Page</fullName>
                <isActive>false</isActive>
                <label>First And Last Page</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Template__c/Document_Template__c.object-meta.xml
<CustomObject>
    <description>Document Template object to store all the different type of forms (Parent of Document Content Object)</description>
    <label>Document Template</label>
    <nameField>
        <label>Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Template__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The template is Active or not</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Document_Template__c/fields/Parent_Template__c.field-meta.xml
<CustomField>
    <fullName>Parent_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Template</label>
    <referenceTo>Document_Template__c</referenceTo>
    <relationshipLabel>Related Templates</relationshipLabel>
    <relationshipName>Related_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Template__c/fields/Template_Type__c.field-meta.xml
<CustomField>
    <fullName>Template_Type__c</fullName>
    <description>The category or type of template.</description>
    <label>Template Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Audit</fullName>
            </value>
            <value>
                <fullName>Regulatory</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Template__c/fields/Template_Version__c.field-meta.xml
<CustomField>
    <fullName>Template_Version__c</fullName>
    <description>Version of the Template</description>
    <label>Template Version</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
    public static List<Document_Template__c> createTemplates(Integer count, String name, String type, Boolean doInsert) {
        List<Document_Template__c> templateList = new List<Document_Template__c>();
        if(String.isBlank(type)) {
            String fieldName = Schema.SObjectType.Document_Template__c.fields.Template_Type__c.getName();
            type = getPicklistValue(SObjectType.Document_Template__c, fieldName, 0);
        }
        for(Integer i = 0; i< count; i++) {
            Document_Template__c template = new Document_Template__c();
            template.Name = name + i;
			template.Template_Version__c = 'V1';
            template.Template_Type__c = type;
            template.Is_Active__c = true;
            templateList.add(template);
        }
        if(doInsert) {
            INSERT templateList;
        }
        return templateList;
    }
    public static List<Document_Template__c> createDefaultTemplates(Integer count, String name, String type, Boolean doInsert) {
      List<Document_Template__c> templateList = new List<Document_Template__c>();
      if(String.isBlank(type)) {
          String fieldName = Schema.SObjectType.Document_Template__c.fields.Template_Type__c.getName();
          type = getPicklistValue(SObjectType.Document_Template__c, fieldName, 0);
      }
      for(Integer i = 0; i< count; i++) {
          Document_Template__c template = new Document_Template__c();
          template.Name = name + i;
    template.Template_Version__c = '1.0';
          template.Template_Type__c = type;
          template.Is_Active__c = true;
          template.Is_Default__c = true;
          //template.Parent_Template__c = createTemplates(1,'Parent Test','Regulatory',true)[0].id;
          templateList.add(template);
      }
      if(doInsert) {
          INSERT templateList;
      }
      return templateList;
  }
    public static List<Corporate_Document__c> createDocuments(Integer count, String stage, Id templateId, Boolean doInsert) {
      List<Corporate_Document__c> docList = new List<Corporate_Document__c>();
      if(String.isBlank(stage)) {
        String fieldName = Schema.SObjectType.Corporate_Document__c.fields.Document_Stage__c.getName();
        stage = getPicklistValue(SObjectType.Corporate_Document__c, fieldName, 0);
      }
      for(Integer i = 0; i< count; i++) {
        Corporate_Document__c doc = new Corporate_Document__c();
        doc.Document_Stage__c = stage;
        doc.Document_Template__c = templateId;
        docList.add(doc);
      }
      if(doInsert) {
          INSERT docList;
      }
      return docList;
  }

    public static List<Document_Content__c> createSections(Integer count, 
                                                            String name, 
                                                            Id templateId, 
                                                            Boolean doInsert) {
      List<Document_Content__c> sectionList = new List<Document_Content__c>();
      for(Integer i = 0; i< count; i++) {
        Document_Content__c section = new Document_Content__c();
        section.Name = name +'-'+ i;
        section.Order_Sequence__c = i + 1;
        section.Section_Content__c = '<p style=\"text-align: center;\"><b><i>TEST CONTENT [Field-0] </i></b></p>';
        section.Document_Template__c = templateId;
        section.Visibility__c = 'All The Pages'; 
        section.Alignment__c = 'Center';
        sectionList.add(section);
      }
      if(doInsert) {
        INSERT sectionList;
      }
      return sectionList;
    }

    public static List<Document_Content__c> createSectionsForDocument(Integer count, 
                                                            String name, 
                                                            Id documentId, 
                                                            Boolean doInsert) {
      List<Document_Content__c> sectionList = new List<Document_Content__c>();
      for(Integer i = 0; i< count; i++) {
        Document_Content__c section = new Document_Content__c();
        section.Name = name +'-'+ i;
        section.Order_Sequence__c = i + 1;
        section.Section_Content__c = '<p style=\"text-align: center;\"><b><i>TEST CONTENT</i></b></p>';
        section.Corporate_Document__c = documentId;
        sectionList.add(section);
      }
      if(doInsert) {
        INSERT sectionList;
      }
      return sectionList;
    }

    public static List<Document_Content__c> createFields(Integer count, 
                                                          String name, 
                                                          List<Document_Content__c> sectionList, 
                                                          Boolean doInsert) {
      List<Document_Content__c> fieldList = new List<Document_Content__c>();
      String fieldName = Schema.SObjectType.Document_Content__c.fields.Field_Type__c.getName();
      String fieldType = getPicklistValue(SObjectType.Document_Content__c, fieldName, 0);
      Integer sectionCount = 0;
      for(Integer i = 0; i< count; i++) {
        Document_Content__c field = new Document_Content__c();
        field.Name = name +'-'+ i;
        field.Order_Sequence__c = i + 1;
        field.Content__c = sectionList[sectionCount].Id;
        field.Field_Type__c = fieldType;
        field.Placeholder_Content__c = field.Name;
        field.Reference_Field__c = 'Account.Name'; 
        field.Visibility__c = 'All The Pages'; 
        fieldList.add(field);
        sectionCount++;
        if(sectionCount == sectionList.size()) {
          sectionCount = 0;
        }
      }
      if(doInsert) {
        INSERT fieldList;
      }
      return fieldList;
    }

    public static List<Domain.SectionWrapper> createSectionWrapsWithFieldWraps(Integer numSecWrap, Integer numFieldWrapsPerSecWrap) {
      List<Domain.SectionWrapper> secWrapList = new List<Domain.SectionWrapper>();
      List<Domain.FieldWrapper> fieldWrapList = new List<Domain.FieldWrapper>();
      String fieldName = Schema.SObjectType.Document_Content__c.fields.Field_Type__c.getName();
      String fieldType = getPicklistValue(SObjectType.Document_Content__c, fieldName, 0);
      for(Integer i = 0; i < numSecWrap; i++) {
        Domain.SectionWrapper secWrap = new Domain.SectionWrapper();
        secWrap.key = 'Section-' + i;
        secWrap.name = 'Section ' + i;
        secWrap.orderSequence = i + 1;
        secWrap.isLandscapeLayout = false;
        secWrap.content = '<p style=\"text-align: center;\"><b><i>TEST CONTENT</i></b></p>';
        fieldWrapList = new List<Domain.FieldWrapper>();
        for(Integer k = 0; k < numFieldWrapsPerSecWrap; k++) {
          Domain.FieldWrapper fieldWrap = new Domain.FieldWrapper();
          fieldWrap.key = secWrap.key + k + 1;
          fieldWrap.sectionKey = secWrap.key;
          fieldWrap.name = 'Field ' + i;
          fieldWrap.type = fieldType;
          fieldWrap.orderSequence = k + 1;
          fieldWrap.placeholderContent = 'Field ' + i;
          fieldWrapList.add(fieldWrap);
        }
        secWrap.fields = fieldWrapList;
        secWrapList.add(secWrap);
      }
      return secWrapList;
  }
    
    public static String getPicklistValue(DescribeSObjectResult objInfo, 
                                          String picklistFieldApiname, 
                                          Integer index) {
        Map<String, Schema.SObjectField> fieldMap = objInfo.fields.getMap();
        List<Schema.PicklistEntry > availableValues = fieldMap.get(picklistFieldApiname).getDescribe().getPickListValues();
        return availableValues[index].getValue();
    }
    
    public static List<Account> createAccounts(Integer count, String name, Boolean doInsert) {
        List<Account> accList = new List<Account>();
        for(Integer i = 0; i< count; i++) {
            Account a = new Account(name = name + i, NumberOfEmployees=100);
            accList.add(a);
        }
        if(doInsert) {
            INSERT accList;
        }
        return accList;
    }
    
    public static List<Contact> createContactsWithAccount(Integer count, String name, Id accId, Boolean doInsert) {
        List<Contact> contactList = new List<Contact>();
        for(Integer i = 0; i< count; i++) {
            Contact con = new Contact(LastName = name + i, Title=name + i, AccountId = accId);
            contactList.add(con);
        }
        if(doInsert) {
            INSERT contactList;
        }
        return contactList;
    }
    
    public static App_Settings__c createCustomSetting() {
        App_Settings__c AppSetting = new App_Settings__c();
        AppSetting.RestAPIVersion__c='v53.0';
        AppSetting.Named_Cred__c='ToolingRest';
        AppSetting.Use_Named_Cred__c=true;
        INSERT AppSetting;
        
        return AppSetting;
    }
}