force-app/main/default/objects/App_Settings__c/App_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>DocuPad App Settings</description>
    <label>App Settings</label>
</CustomObject>

force-app/main/default/objects/App_Settings__c/fields/DocumentCSS__c.field-meta.xml
<CustomField>
    <fullName>DocumentCSS__c</fullName>
    <description>This field is to defined custom CSS for Document</description>
    <inlineHelpText>Custom CSS for Document</inlineHelpText>
    <label>DocumentCSS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Corporate_Document__c/Corporate_Document__c.object-meta.xml
<CustomObject>
    <description>Corporate Document Objects stores the Uncompleted Documents</description>
    <label>Corporate Document</label>
    <nameField>
        <label>Document</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Corporate Document</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Corporate_Document__c/fields/Document_Stage__c.field-meta.xml
<CustomField>
    <fullName>Document_Stage__c</fullName>
    <description>Stage of Document</description>
    <label>Document Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Obsolete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Corporate_Document__c/fields/Document_Template__c.field-meta.xml
<CustomField>
    <fullName>Document_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LookUp to Document Template to store the template as draft</description>
    <label>Document Template</label>
    <referenceTo>Document_Template__c</referenceTo>
    <relationshipLabel>Corporate Document</relationshipLabel>
    <relationshipName>Corporate_Document</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Content__c/Document_Content__c.object-meta.xml
<CustomObject>
    <description>Content Objects holds all the content of the Form (Child of Form Object)</description>
    <label>Document Content</label>
    <nameField>
        <label>Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Content</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Content__c/fields/Alignment__c.field-meta.xml
<CustomField>
    <fullName>Alignment__c</fullName>
    <description>To Specify alignment of page header/footer content.</description>
    <label>Alignment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Left</fullName>
            </value>
            <value>
                <fullName>Center</fullName>
            </value>
            <value>
                <fullName>Right</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Content__c/fields/Content_Type__c.field-meta.xml
<CustomField>
    <fullName>Content_Type__c</fullName>
    <description>To Differentiate body content other non body contents like Header, Footer, Page Break and Blank Page.</description>
    <label>Content Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Body</fullName>
                <default>true</default>
                <label>Body</label>
            </value>
            <value>
                <fullName>Header</fullName>
            </value>
            <value>
                <fullName>Footer</fullName>
            </value>
            <value>
                <fullName>Page Break</fullName>
            </value>
            <value>
                <fullName>Blank Page</fullName>
            </value>
            <value>
                <fullName>Related Records</fullName>
            </value>
            <value>
                <fullName>Custom Content</fullName>
            </value>
            <value>
                <fullName>Signature</fullName>
                <isActive>false</isActive>
                <label>Signature</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Content__c/fields/Corporate_Document__c.field-meta.xml
<CustomField>
    <fullName>Corporate_Document__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up to a document.</description>
    <label>Corporate Document</label>
    <referenceTo>Corporate_Document__c</referenceTo>
    <relationshipLabel>Document Content</relationshipLabel>
    <relationshipName>CorpContents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Content__c/fields/Document_Template__c.field-meta.xml
<CustomField>
    <fullName>Document_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up to the document template object, in order to relate section content to the document template.</description>
    <label>Document Template</label>
    <referenceTo>Document_Template__c</referenceTo>
    <relationshipLabel>Document Content</relationshipLabel>
    <relationshipName>TempContents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Content__c/fields/Enable_Landscape_Layout__c.field-meta.xml
<CustomField>
    <fullName>Enable_Landscape_Layout__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enables the landscape page layout for the section if checked otherwise portrait page layout.</description>
    <label>Enable Landscape Layout</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Document_Content__c/fields/Order_Sequence__c.field-meta.xml
<CustomField>
    <fullName>Order_Sequence__c</fullName>
    <description>Order in which the section content should be displayed for a template or document.</description>
    <label>Order Sequence</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Document_Content__c/fields/Section_Content__c.field-meta.xml
<CustomField>
    <fullName>Section_Content__c</fullName>
    <description>Holds the section contents in the form of html markup text.</description>
    <label>Section Content</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Document_Content__c/fields/Visibility__c.field-meta.xml
<CustomField>
    <fullName>Visibility__c</fullName>
    <description>Decides the visibility of header/footer content of the page to be on All The Pages or on First Page Only.</description>
    <label>Visibility</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>First Page Only</fullName>
            </value>
            <value>
                <fullName>All The Pages</fullName>
            </value>
            <value>
                <fullName>First And Last Page</fullName>
                <isActive>false</isActive>
                <label>First And Last Page</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Template__c/Document_Template__c.object-meta.xml
<CustomObject>
    <description>Document Template object to store all the different type of forms (Parent of Document Content Object)</description>
    <label>Document Template</label>
    <nameField>
        <label>Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Template__c/fields/Page_Size__c.field-meta.xml
<CustomField>
    <fullName>Page_Size__c</fullName>
    <label>Page Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A3</fullName>
            </value>
            <value>
                <fullName>A4</fullName>
            </value>
            <value>
                <fullName>US Legal</fullName>
            </value>
            <value>
                <fullName>US Letter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ViewPDFController.cls
public with sharing class ViewPDFController {

    public static final String BODY = 'Body';
    public static final String HEADER = 'Header';
    public static final String FOOTER = 'Footer';
    public static final String RELATED_RECORDS = 'Related Records';
    public static final String CUSTOM_CONTENT = 'Custom Content';
    public static final String ALL_THE_PAGES = 'All The Pages';
    public static final String FIRST_PAGE_ONLY = 'First Page Only';
    public static final String PAGE_BREAK = 'Page Break';
    public static final String BLANK_PAGE = 'Blank Page';
    public static final String DEFAULT_CSSFILE= 'DocumentCSS';
    public static final String DEFAULT_DOCTYPE= 'PDF';
    public static final String DEFAULT_PAGESIZE= 'A4';
    public static Corporate_Document__c corpDoc {get;set;}
    public static String allPageHeader {get;set;}
    public static String allPageFooter {get;set;}
    public static String firstPageHeader {get;set;}
    public static String firstPageFooter {get;set;}
    public static String headerAlignment {get;set;}
    public static String footerAlignment {get;set;}
    public static boolean isPageBreakLast {get;set;}
    public static String pagesize {get;set;}
    public static List<WrapperDocument> wrContentDocumentLst {get;set;}
    

    public static Id corpDocId = System.currentPagereference().getParameters().get('id');
    //ABDS:s:Pass Value from Custom setting
    public static String DocumentCSS { get; set; }
    public static App_Settings__c App_Setting= App_Settings__c.getOrgDefaults();
    public static string ViewAs= System.currentPagereference().getParameters().get('viewas');
    public static String DocType{ get; set; }
    public static String ContentType{ get; set; }
     
    public static void loadPageContents() {
        pagesize=DEFAULT_PAGESIZE;
        wrContentDocumentLst = new List<WrapperDocument>();
        DocumentCSS=DEFAULT_CSSFILE;
        ViewAs=string.Isblank(ViewAs)?DEFAULT_DOCTYPE:ViewAs;
        ContentType='';
        DocType=DEFAULT_DOCTYPE;
        
        if (string.isNotBlank(App_Setting.DocumentCSS__c ))
        {
            DocumentCSS=App_Setting.DocumentCSS__c;
        }
        
        
        if (ViewAs=='word')
        {   
            DocType=''; 
            ContentType='application/msword';
        }
        else if (ViewAs=='excel')
        {
            DocType='';
            ContentType='application/vnd.ms-excel';
        }
        loadPageBodyContents();
        firstPageHeader = loadPageMarginContents(HEADER, FIRST_PAGE_ONLY);
        if(String.isBlank(firstPageHeader)) {
            allPageHeader = loadPageMarginContents(HEADER, ALL_THE_PAGES);
        }
        firstPageFooter = loadPageMarginContents(FOOTER, FIRST_PAGE_ONLY);
        if(String.isBlank(firstPageFooter)) {
            allPageFooter = loadPageMarginContents(FOOTER, ALL_THE_PAGES);
        }
    }
    
    private static void loadPageBodyContents() {
        List<Corporate_Document__c> corpDocList = new List<Corporate_Document__c>();
        corpDocList = [SELECT Id, Name, Document_Template__c, Document_Stage__c,Document_Template__r.Page_Size__c,
                            (SELECT Id, Section_Content__c, Content_Type__c, Enable_Landscape_Layout__c
                            FROM CorpContents__r
                            WHERE (Content_Type__c = :BODY OR Content_Type__c = :RELATED_RECORDS 
                            OR Content_Type__c = :PAGE_BREAK OR Content_Type__c = :BLANK_PAGE
                            OR Content_Type__c = :CUSTOM_CONTENT)
                            ORDER BY Order_Sequence__c ASC
                            NULLS LAST)
                        FROM Corporate_Document__c
                        WHERE Id = :corpDocId WITH SECURITY_ENFORCED]; 
        if(!corpDocList.isEmpty()) {
            corpDoc = corpDocList[0];
            if (string.isNotBlank( corpDoc.Document_Template__r.Page_Size__c))
            {
                pagesize=corpDoc.Document_Template__r.Page_Size__c;
            }
        }
        Integer i=1;
        for(Document_Content__c obj : corpDoc.CorpContents__r) {
            WrapperDocument wrDocObj = new WrapperDocument();
            wrDocObj.contentId = obj.Id;
            wrDocObj.contentType = obj.Content_Type__c;
            wrDocObj.enableLandscape = obj.Enable_Landscape_Layout__c;
            wrDocObj.sectionContent = obj.Section_Content__c;
            wrDocObj.enablePageBeak = false;
            if(obj.Content_Type__c == 'Page Break') {
                wrDocObj.enablePageBeak = checkEnablePageBreak(obj.Id, corpDoc.CorpContents__r);
            }
            if(corpDoc.CorpContents__r.size() == i && obj.Content_Type__c == 'Blank Page'){
                wrDocObj.isLastBlankPage = true;
            } else{
                wrDocObj.isLastBlankPage = false;
            }
            i=i+1;
            wrContentDocumentLst.add(wrDocObj);
        }
    }

    private static Boolean checkEnablePageBreak(string contentId,List<Document_Content__c> documentContentLst) {
        boolean flag = false;
        for(Document_Content__c obj : documentContentLst) {
            if(flag && obj.Content_Type__c != 'Page Break') {
                return true;
            }
            if(obj.Id == contentId) {
                flag = true;
            }
        }
        return false;
    }

    private static String loadPageMarginContents(String marginDiv, String visibility) {
        String marginContent;
        List<Document_Content__c> sectionList = new List<Document_Content__c>();
        sectionList = [SELECT Id, Section_Content__c, Content_Type__c, Alignment__c
                        FROM Document_Content__c
                        WHERE Content_Type__c = :marginDiv
                        AND Visibility__c = :visibility
                        AND Corporate_Document__c = :corpDocId
                        WITH SECURITY_ENFORCED
                        ORDER BY Order_Sequence__c ASC
                        NULLS LAST]; 
        if(!sectionList.isEmpty()) {
            if(marginDiv == HEADER) {
                headerAlignment = sectionList[0].Alignment__c;
            } else if(marginDiv == FOOTER) {
                footerAlignment = sectionList[0].Alignment__c;
            }
            marginContent = sectionList[0].Section_Content__c;
            //marginContent = marginContent.replace('<p>','').replace('</p>','');
        }
        return marginContent;
    }

    public class WrapperDocument {
        public String contentType {get;set;}
        public String contentId {get;set;}
        public boolean enableLandscape {get;set;}
        public String sectionContent {get;set;}
        public boolean enablePageBeak {get;set;}
        public boolean isLastBlankPage {get;set;}
    }

}