force-app/main/default/objects/Data_Sources__c/Data_Sources__c.object-meta.xml
<CustomObject>
    <label>Data Source</label>
    <nameField>
        <label>Data Source Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Sources__c/fields/Document_Template__c.field-meta.xml
<CustomField>
    <fullName>Document_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Document Template</label>
    <referenceTo>Document_Template__c</referenceTo>
    <relationshipLabel>Data Sources</relationshipLabel>
    <relationshipName>Data_Sources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Data_Sources__c/fields/Handler_Name__c.field-meta.xml
<CustomField>
    <fullName>Handler_Name__c</fullName>
    <label>Handler Name</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Data_Sources__c/fields/Inputs__c.field-meta.xml
<CustomField>
    <fullName>Inputs__c</fullName>
    <label>Inputs</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Sources__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>restApi</fullName>
            </value>
            <value>
                <fullName>query</fullName>
            </value>
            <value>
                <fullName>channelName</fullName>
            </value>
            <value>
                <fullName>className</fullName>
            </value>
            <value>
                <fullName>object</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Template__c/Document_Template__c.object-meta.xml
<CustomObject>
    <description>Document Template object to store all the different type of forms (Parent of Document Content Object)</description>
    <label>Document Template</label>
    <nameField>
        <label>Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Template__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description says what is this form for..? and where it is used..?</description>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Document_Template__c/fields/Parent_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_Object_Name__c</fullName>
    <label>Object</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Template__c/fields/Template_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Template_External_Id__c</fullName>
    <description>Template External Id used to import the templates.</description>
    <externalId>true</externalId>
    <label>Template External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/lwapic__Integration_Channel__c/lwapic__Integration_Channel__c.object-meta.xml
<CustomObject>
    <description>Integration Channel</description>
    <label>Integration Channel</label>
    <nameField>
        <label>Channel Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/lwapic__Integration_Channel__c/fields/lwapic__Channel_Name__c.field-meta.xml
<CustomField>
    <fullName>lwapic__Channel_Name__c</fullName>
    <description>Unique Channel Name</description>
    <inlineHelpText>Please provide a unique channel name. 
This will be used in the Process Builder, Flow and Apex to identify the channel.</inlineHelpText>
    <label>Channel Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/DataSourceController.cls
public with sharing class DataSourceController {

    @AuraEnabled
    public static List<Object> FetchDataSource(String doucumentTemplateId ){
      //  List<Object> listOfDataSources = new List<Object>();
        List<Document_Template__c> listOFDocumentTemplate = [SELECT Id, Name,Parent_Object_Name__c,Template_External_Id__c, (SELECT Id, Name, Order__c,Handler_Name__c,Type__c, Document_Template__c, Active__c,Description__c,Inputs__c FROM Data_Sources__r ORDER BY Order__c ASC) FROM Document_Template__c WHERE Document_Template__c.Id = :doucumentTemplateId ];
       // List<PackageLicense> listOfPackages =[SELECT Id, NamespacePrefix FROM PackageLicense];
         // System.debug('listOfPackages'+listOfPackages);
         // listOfDataSources.add(listOFDocumentTemplate);
         // listOfDataSources.add(listOfPackages);
          //system.debug('listOfDataSources'+listOfDataSources);
          return listOFDocumentTemplate; 
    }
    @AuraEnabled
    public static List<Data_Sources__c> SaveDataSource (String dataSource) {
        List<Data_Sources__c> dataSourceList  = (List<Data_Sources__c>) JSON.deserialize(dataSource, List<Data_Sources__c>.class);
       // List<Data_Sources__c> dataSourceList  = (List<Data_Sources__c>) JSON.deserializeUntyped(dataSource);
        UPSERT dataSourceList;
        return dataSourceList;
    }
    @AuraEnabled
      public static void deleteDataSources (String strId, String updatedArr) {
          System.debug('strId'+strId);
          System.debug('updatedArr'+updatedArr);
          SObject obj = [SELECT Id From Data_Sources__c Where Id=:strId];
          delete obj;
          System.debug('--=-- inside the update data --=--');
          List<Data_Sources__c> dataSourceList  = (List<Data_Sources__c>) JSON.deserialize(updatedArr, List<Data_Sources__c>.class);
          System.debug('--=-- inside the update data after --=--');
          UPDATE dataSourceList;
    }   
    @AuraEnabled 
      public static List<SObject> getIntegrationChannel (String searchKey){
        String keyString ='%'+ searchKey + '%';
        return [
            SELECT lwapic__Channel_Name__c, Id FROM lwapic__Integration_Channel__c WHERE lwapic__Channel_Name__c like:keyString
            ];
    }
    @AuraEnabled
    public static List<SObject> getAllApexClasses(String searchKey){
        String keyString ='%'+ searchKey + '%';
        return[SELECT Name FROM ApexClass WHERE Name like:keyString];
    }
        @AuraEnabled
    public static List<SObject> queryMetadata(String serviceName ){
        String query ='SELECT Id,QualifiedApiName, Carbone_url__c, Method__c, Carbone_Version__c, Authorization_Token__c FROM Carbone_Info__mdt WHERE QualifiedApiName='+'\''+ serviceName + '\'';
        List<SObject> lstRecords = Database.query(query);
        System.debug('lstRecords = '+lstRecords);
        return lstRecords;
    }
}